. "$PSScriptRoot\command-policy.ps1"

Set-DxSerialBuildEnvironment
Assert-DxDriveSpace -MinimumFreeGiB 3
Assert-NoCompetingHeavyProcess

Push-Location (Resolve-Path "$PSScriptRoot\..")
try {
    Invoke-DxCommand "npm" @("run", "test:command-policy-runtime")
    Invoke-DxCommand "npm" @("run", "test:host-package-script-policy")
    Invoke-DxCommand "npm" @("run", "test:host-product-surface-copy-policy")
    Invoke-DxCommand "npm" @("run", "test:j1-wrapper-process-guards")
    Invoke-DxCommand "npm" @("run", "test:typescript-source-extensions")
    Invoke-DxCommand "npm" @("run", "check:generated-output-ignore")
    Invoke-DxCommand "npm" @("run", "test:official-registry")
    Invoke-DxCommand "npm" @("run", "test:extension-readiness")
    Invoke-DxCommand "npm" @("run", "test:source-readiness-receipts")
    Invoke-DxCommand "npm" @("run", "test:operator-proof-template")
    Invoke-DxCommand "npm" @("run", "test:loaded-host-preflight-receipts")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-environment-summary")
    Invoke-DxCommand "npm" @("run", "test:platform-host-discovery-receipts")
    Invoke-DxCommand "npm" @("run", "test:extension-progress-report")
    Invoke-DxCommand "npm" @("run", "test:extension-progress-report-affinity-content")
    Invoke-DxCommand "npm" @("run", "test:extension-progress-stale-readiness")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gates")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report-affinity-content-package")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report-browser-blockers")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report-browser-distribution-targets")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report-adobe-plugin-id-gate")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report-checksum-artifact")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report-core-evidence")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report-visual-studio-package-output")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report-ide-game-engine")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report-ide-game-engine-package-output")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report-ide-game-engine-environment")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report-creative-loaded-host")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report-office-local-service")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report-remediation")
    Invoke-DxCommand "npm" @("run", "test:host-free-release-artifact-refresh-plan")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report-special-evidence")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report-signing-review-freshness")
    Invoke-DxCommand "npm" @("run", "test:extension-starter")
    Invoke-DxCommand "npm" @("run", "test:professional-host-targets")
    Invoke-DxCommand "npm" @("run", "test:vscode-package-output-receipt")
    Invoke-DxCommand "npm" @("run", "test:vscode-loaded-host-proof-receipts")
    Invoke-DxCommand "npm" @("run", "test:browser-host-action-index-receipt")
    Invoke-DxCommand "npm" @("run", "test:browser-package-output-receipt")
    Invoke-DxCommand "npm" @("run", "test:browser-loaded-profile-receipt")
    Invoke-DxCommand "npm" @("run", "test:browser-extension-id-capture")
    Invoke-DxCommand "npm" @("run", "test:browser-loaded-profile-smoke-runner")
    Invoke-DxCommand "npm" @("run", "test:browser-native-host-package-receipt")
    Invoke-DxCommand "npm" @("run", "test:browser-native-host-package-preflight")
    Invoke-DxCommand "npm" @("run", "test:browser-loaded-profile-proof-receipts")
    Invoke-DxCommand "npm" @("run", "test:package-output-checksum-receipts")
    Invoke-DxCommand "npm" @("run", "test:release-package-checksum-receipts")
    Invoke-DxCommand "npm" @("run", "test:affinity-release-package-checksum")
    Invoke-DxCommand "npm" @("run", "test:office-google-release-package-checksum")
    Invoke-DxCommand "npm" @("run", "test:package-output-release-package-checksum")
    Invoke-DxCommand "npm" @("run", "test:current-package-output-archive-proof")
    Invoke-DxCommand "npm" @("run", "test:package-signing-receipt")
    Invoke-DxCommand "npm" @("run", "test:package-notarization-receipt")
    Invoke-DxCommand "npm" @("run", "test:distribution-review-receipts")
    Invoke-DxCommand "npm" @("run", "test:blender-adapter")
    Invoke-DxCommand "npm" @("run", "test:blender-package-output")
    Invoke-DxCommand "npm" @("run", "test:blender-package-output-receipt")
    Invoke-DxCommand "npm" @("run", "test:obsidian-adapter")
    Invoke-DxCommand "npm" @("run", "test:obsidian-build-output")
    Invoke-DxCommand "npm" @("run", "test:obsidian-package-output-receipt")
    Invoke-DxCommand "npm" @("run", "test:figma-adapter")
    Invoke-DxCommand "npm" @("run", "test:figma-build-output")
    Invoke-DxCommand "npm" @("run", "test:figma-loaded-host-receipts")
    Invoke-DxCommand "npm" @("run", "test:application-loaded-host-receipts")
    Invoke-DxCommand "npm" @("run", "test:canva-adapter")
    Invoke-DxCommand "npm" @("run", "test:canva-build-output")
    Invoke-DxCommand "npm" @("run", "test:figma-canva-package-output-receipts")
    Invoke-DxCommand "npm" @("run", "test:canva-cloud-service-receipt")
    Invoke-DxCommand "npm" @("run", "test:sketch-adapter")
    Invoke-DxCommand "npm" @("run", "test:sketch-build-output")
    Invoke-DxCommand "npm" @("run", "test:sketch-package-output-receipt")
    Invoke-DxCommand "npm" @("run", "test:creative-host-checksum-receipts")
    Invoke-DxCommand "npm" @("run", "check:office-local-service-boundary")
    Invoke-DxCommand "npm" @("run", "test:office-taskpane-asset-output")
    Invoke-DxCommand "npm" @("run", "test:office-sideload-manifest-output")
    Invoke-DxCommand "npm" @("run", "test:office-package-output-receipts")
    Invoke-DxCommand "npm" @("run", "test:office-sideloaded-host-receipts")
    Invoke-DxCommand "npm" @("run", "test:office-local-service-receipts")
    Invoke-DxCommand "npm" @("run", "test:local-service-receipts")
    Invoke-DxCommand "npm" @("run", "test:excel-adapter")
    Invoke-DxCommand "npm" @("run", "test:powerpoint-adapter")
    Invoke-DxCommand "npm" @("run", "test:word-adapter")
    Invoke-DxCommand "npm" @("run", "test:zed-adapter")
    Invoke-DxCommand "npm" @("run", "test:zed-build-output")
    Invoke-DxCommand "npm" @("run", "test:zed-package-output-receipt")
    Invoke-DxCommand "npm" @("run", "test:photoshop-adapter")
    Invoke-DxCommand "npm" @("run", "test:premiere-pro-adapter")
    Invoke-DxCommand "npm" @("run", "test:indesign-adapter")
    Invoke-DxCommand "npm" @("run", "test:adobe-uxp-package-output")
    Invoke-DxCommand "npm" @("run", "test:adobe-uxp-package-output-receipts")
    Invoke-DxCommand "npm" @("run", "test:adobe-ccx-package-builder")
    Invoke-DxCommand "npm" @("run", "test:adobe-ccx-package-receipts")
    Invoke-DxCommand "npm" @("run", "test:adobe-ccx-release-checksum-builder")
    Invoke-DxCommand "npm" @("run", "test:adobe-uxp-plugin-id-receipt")
    Invoke-DxCommand "npm" @("run", "test:davinci-resolve-adapter")
    Invoke-DxCommand "npm" @("run", "test:davinci-resolve-package-output-receipt")
    Invoke-DxCommand "npm" @("run", "test:davinci-resolve-developer-docs-receipt")
    Invoke-DxCommand "npm" @("run", "test:davinci-resolve-developer-docs-wrapper")
    Invoke-DxCommand "npm" @("run", "test:creative-loaded-host-receipts")
    Invoke-DxCommand "npm" @("run", "test:creative-native-or-hybrid-plugin-receipts")
    Invoke-DxCommand "npm" @("run", "test:intellij-platform-plugin-adapter")
    Invoke-DxCommand "npm" @("run", "test:intellij-platform-package-output-receipt")
    Invoke-DxCommand "npm" @("run", "test:visual-studio-sdk-plugin-adapter")
    Invoke-DxCommand "npm" @("run", "test:visual-studio-package-output-receipt")
    Invoke-DxCommand "npm" @("run", "test:unity-editor-plugin-adapter")
    Invoke-DxCommand "npm" @("run", "test:unity-editor-package-output-receipt")
    Invoke-DxCommand "npm" @("run", "test:unreal-engine-plugin-adapter")
    Invoke-DxCommand "npm" @("run", "test:unreal-engine-package-output-receipt")
    Invoke-DxCommand "npm" @("run", "test:ide-game-engine-loaded-host-receipts")
    Invoke-DxCommand "npm" @("run", "test:ide-game-engine-special-proof-receipts")
    Invoke-DxCommand "npm" @("run", "test:release-evidence-gap-report-ide-game-engine-loaded-host")
    Invoke-DxCommand "npm" @("run", "test:google-workspace-addon-adapter")
    Invoke-DxCommand "npm" @("run", "test:google-workspace-apps-script-output")
    Invoke-DxCommand "npm" @("run", "test:google-workspace-apps-script-package-output-receipt")
    Invoke-DxCommand "npm" @("run", "test:google-workspace-deployment-receipts")
    Invoke-DxCommand "npm" @("run", "test:affinity-content-addon-adapter")
    Invoke-DxCommand "npm" @("run", "test:affinity-content-package-output")
    Invoke-DxCommand "npm" @("run", "test:affinity-content-package-receipt")
    Invoke-DxCommand "npm" @("run", "test:affinity-manual-import-receipt")
    Invoke-DxCommand "npm" @("run", "test:affinity-loaded-app-receipt")
    Invoke-DxCommand "npm" @("run", "test:affinity-photoshop-filter-plugin-receipt")
    Invoke-DxCommand "npm" @("run", "test:native-host-command-boundary")
    Invoke-DxCommand "npm" @("--workspace", "dx-vscode", "run", "test:command-plans")
    Invoke-DxCommand "npm" @("--workspace", "dx-vscode", "run", "test:manifest-command-parity")
    Invoke-DxCommand "npm" @("--workspace", "dx-vscode", "run", "test:command-surface")
    Invoke-DxCommand "npm" @("--workspace", "dx-browser", "run", "test:command-plans")
    Invoke-DxCommand "npm" @("--workspace", "dx-browser", "run", "test:protocol")
    Invoke-DxCommand "npm" @("--workspace", "dx-browser", "run", "test:manifests")
    Invoke-DxCommand "npm" @("--workspace", "dx-browser", "run", "test:manifest-protocol")
    Invoke-DxCommand "npm" @("--workspace", "dx-browser", "run", "test:native-surface")
    Invoke-DxCommand "npm" @("--workspace", "dx-browser", "run", "test:native-host-manifests")
    Invoke-DxCommand "npm" @("--workspace", "dx-browser", "run", "test:native-host-install-proof")
    Invoke-DxCommand "npm" @("--workspace", "dx-browser", "run", "test:native-host-shell-install-proof")
    Invoke-DxCommand "npm" @("--workspace", "dx-browser", "run", "test:native-host-shell-uninstall-proof")
    Invoke-DxCommand "npm" @("--workspace", "dx-browser", "run", "test:native-host-transport")
    Invoke-DxCommand "npm" @("--workspace", "dx-browser", "run", "test:background-dispatch")
    Invoke-DxCommand "npm" @("--workspace", "dx-browser", "run", "test:background-entrypoints")
    Invoke-DxCommand "npm" @("--workspace", "dx-browser", "run", "test:ui-dispatch")
    Invoke-DxCommand "cargo" @("test", "-j", "1", "--workspace")
    Invoke-DxCommand "npm" @("run", "smoke:browser-native-host:j1")
    Invoke-DxCommand "node" @("--experimental-strip-types", "scripts/write-source-readiness-receipts.ts", "--verification-command", "npm run test:j1")
}
finally {
    Pop-Location
}
